# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:
    cmds:
      - go test github.com/FFengIll/go-thrift
      - go test github.com/FFengIll/go-thrift/parser
      - go test github.com/FFengIll/go-thrift/thrift

  install:
    cmds:
      - go install github.com/mna/pigeon 

  gen:
    cmds:
      - go generate ./parser